name: Build on Windows

on:
    workflow_call:
        inputs:
            commit-sha:
                type: string
                required: true
        outputs:
            runid:
                value: ${{github.run_id}}
    workflow_dispatch:
        inputs:
            commit-sha:
                type: string
                description: Target commit
                required: true

jobs:
    build:
        runs-on: windows-latest
        steps:

          - name: Checkout Wasmer
            uses: actions/checkout@v4
            with:
                repository: wasmerio/wasmer
                path: wasmer
                ref: ${{inputs.commit-sha}}
                submodules: recursive

          - name: Install Rust
            uses: dtolnay/rust-toolchain@v1
            with:
                toolchain: stable
                targets: x86_64-pc-windows-msvc

          - name: Install LLVM 18
            shell: pwsh
            run: |
                mkdir llvm
                cd llvm
                wget -O llvm.tar.xz https://github.com/wasmerio/llvm-custom-builds/releases/download/18.x/llvm-windows-amd64.tar.xz
                7z x llvm.tar.xz
                7z x llvm.tar
                "LLVM_SYS_180_PREFIX=${{github.workspace}}/llvm" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
                "LLVM_CONFIG_PATH=${{github.workspace}}/llvm/bin/llvm-config.exe" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
                "${{github.workspace}}/llvm/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

          - name: Build Windows x64 Debug
            shell: pwsh
            run: |
                cd wasmer
                cargo rustc -p wasmer-c-api --target x86_64-pc-windows-msvc --no-default-features --features "llvm,wat,staticlib" -- -Cdebuginfo=2 -Ctarget-feature=+crt-static --crate-type=staticlib

          - name: Build Windows x64 Release
            shell: pwsh
            run: |
                cd wasmer
                cargo rustc -p wasmer-c-api --target x86_64-pc-windows-msvc --no-default-features --features "llvm,wat,staticlib" --release -- -Ctarget-feature=+crt-static --crate-type=staticlib

          - name: Compress Product
            shell: pwsh
            run: |
                echo ${{inputs.commit-sha}} >> VERSION.txt
                mkdir temp\include
                cp -r wasmer\lib\c-api\tests\wasm-c-api\include\* temp\include
                cp wasmer\lib\c-api\wasmer.h temp\include
                cp wasmer\lib\c-api\wasmer_wasm.h temp\include
                7z a wasmer_windows_x64_debug.7z .\wasmer\target\x86_64-pc-windows-msvc\debug\wasmer.lib .\wasmer\target\x86_64-pc-windows-msvc\debug\wasmer.pdb .\temp\include VERSION.txt
                7z a wasmer_windows_x64_release.7z .\wasmer\target\x86_64-pc-windows-msvc\release\wasmer.lib .\temp\include VERSION.txt

          - name: Upload Archive
            uses: actions/upload-artifact@v4
            with:
                name: wasmer_windows
                path: |
                    *.7z
                retention-days: 7