name: Build on Linux

on:
    workflow_call:
        inputs:
            commit-sha:
                type: string
                required: true
        outputs:
            runid:
                value: ${{github.run_id}}
    workflow_dispatch:
        inputs:
            commit-sha:
                type: string
                description: Target commit
                required: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            
          - name: stop
            shell: bash
            run: ffeuhifweui

          - name: Checkout BGFX
            uses: actions/checkout@v4
            with:
                repository: bkaradzic/bgfx
                path: bgfx
        
          - name: Checkout BX
            uses: actions/checkout@v4
            with:
                repository: bkaradzic/bx
                path: bx

          - name: Checkout BIMG
            uses: actions/checkout@v4
            with:
                repository: bkaradzic/bimg
                path: bimg

          - name: Install Dependencies
            shell: bash
            run: |
                sudo apt update
                sudo apt install libgl-dev
                sudo dpkg --add-architecture arm64
                sudo sed -ri '/^Components:/a Architectures: amd64' "/etc/apt/sources.list.d/ubuntu.sources"
                sudo tee /etc/apt/sources.list.d/ubuntu-ports.list >/dev/null <<'EOF'
                    deb [arch=arm64 signed-by=/usr/share/keyrings/ubuntu-archive-keyring.gpg] http://ports.ubuntu.com/ubuntu-ports noble main universe restricted multiverse
                    deb [arch=arm64 signed-by=/usr/share/keyrings/ubuntu-archive-keyring.gpg] http://ports.ubuntu.com/ubuntu-ports noble-updates main universe restricted multiverse
                    deb [arch=arm64 signed-by=/usr/share/keyrings/ubuntu-archive-keyring.gpg] http://ports.ubuntu.com/ubuntu-ports noble-backports main universe restricted multiverse
                    deb [arch=arm64 signed-by=/usr/share/keyrings/ubuntu-archive-keyring.gpg] http://ports.ubuntu.com/ubuntu-ports noble-security main universe restricted multiverse
                EOF
                sudo apt update
                sudo apt install g++-aarch64-linux-gnu libgl-dev:arm64

          - name: Build Linux x64
            shell: bash
            run: |
                cd bgfx
                ../bx/tools/bin/linux/genie --with-tools --gcc=linux-gcc --platform=x64 gmake
                cd .build/projects/gmake-linux-gcc
                make -j$(nproc) config=debug64 CFLAGS="-O0 -g3 -fno-omit-frame-pointer" CXXFLAGS="-O0 -g3 -fno-omit-frame-pointer" bgfx bimg bx
                make -j$(nproc) config=release64 bgfx bimg bx shaderc

          - name: Build Linux arm64
            shell: bash
            run: |
                sudo update-alternatives --install /usr/bin/strip strip /usr/bin/aarch64-linux-gnu-strip 100
                cd bgfx
                ../bx/tools/bin/linux/genie --with-tools --gcc=linux-arm-gcc --platform=ARM64 gmake
                cd .build/projects/gmake-linux-arm-gcc
                sed -i 's/-m64//g' *
                make -j$(nproc) ARCH= CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ AR=aarch64-linux-gnu-ar RANLIB=aarch64-linux-gnu-ranlib config=debug64 CFLAGS="-O0 -g3 -fno-omit-frame-pointer" CXXFLAGS="-O0 -g3 -fno-omit-frame-pointer" bgfx bimg bx
                make -j$(nproc) ARCH= CC=aarch64-linux-gnu-gcc CXX=aarch64-linux-gnu-g++ AR=aarch64-linux-gnu-ar RANLIB=aarch64-linux-gnu-ranlib config=release64 bgfx bimg bx shaderc

          - name: Compress Product
            shell: bash
            run: |
                echo ${{inputs.commit-sha}} >> VERSION.txt
                mkdir -p temp/include
                cp -a bgfx/include/* temp/include
                cp -a bx/include/* temp/include
                cp -a bimg/include/* temp/include
                mkdir x64
                mkdir arm64
                mv bgfx/.build/linux64_gcc/bin/shadercRelease x64/shaderc
                mv bgfx/.build/linux32_arm_gcc/bin/shadercRelease arm64/shaderc
                7z a bgfx_linux_x64_debug.7z ./bgfx/.build/linux64_gcc/bin/libbgfxDebug.a ./bgfx/.build/linux64_gcc/bin/libbxDebug.a ./bgfx/.build/linux64_gcc/bin/libbimgDebug.a ./x64/shaderc ./temp/include VERSION.txt
                7z a bgfx_linux_x64_release.7z ./bgfx/.build/linux64_gcc/bin/libbgfxRelease.a ./bgfx/.build/linux64_gcc/bin/libbxRelease.a ./bgfx/.build/linux64_gcc/bin/libbimgRelease.a ./x64/shaderc ./temp/include VERSION.txt
                7z a bgfx_linux_arm64_debug.7z ./bgfx/.build/linux32_arm_gcc/bin/libbgfxDebug.a ./bgfx/.build/linux32_arm_gcc/bin/libbxDebug.a ./bgfx/.build/linux32_arm_gcc/bin/libbimgDebug.a ./arm64/shaderc ./temp/include VERSION.txt
                7z a bgfx_linux_arm64_release.7z ./bgfx/.build/linux32_arm_gcc/bin/libbgfxRelease.a ./bgfx/.build/linux32_arm_gcc/bin/libbxRelease.a ./bgfx/.build/linux32_arm_gcc/bin/libbimgRelease.a ./arm64/shaderc ./temp/include VERSION.txt

          - name: Upload Archive
            uses: actions/upload-artifact@v4
            with:
                name: bgfx_linux
                path: |
                    *.7z
                retention-days: 7