name: Build on Linux

on:
    workflow_call:
        inputs:
            commit-sha:
                type: string
                required: true
        outputs:
            runid:
                value: ${{github.run_id}}
    workflow_dispatch:
        inputs:
            commit-sha:
                type: string
                description: Target commit
                required: true

jobs:
    x64:
        runs-on: ubuntu-latest
        steps:

          - name: Checkout Wasmer
            uses: actions/checkout@v4
            with:
                repository: wasmerio/wasmer
                path: wasmer
                ref: ${{inputs.commit-sha}}
                submodules: recursive

          - name: Install Rust
            uses: dtolnay/rust-toolchain@v1
            with:
                toolchain: stable
                targets: x86_64-unknown-linux-gnu

          - name: Resolve LLVM Version
            shell: bash
            id: llvm
            run: |
                cd wasmer
                $metajson = cargo metadata --format-version=1 --features "wasmer-c-api/llvm,wasmer-c-api/wat" --no-default-features | ConvertFrom-Json -AsHashTable
                $pkg = $metajson.packages | Where-Object { $_.name -eq "llvm-sys" } | Select-Object -First 1
                $sysMajor = [int]($pkg.version.Split('.')[0])
                $llvmMajor = [math]::Floor($sysMajor / 10)
                $llvmMinor = $sysMajor % 10
                "sysMajor=$sysMajor" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
                "llvmMajor=$llvmMajor" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
                "llvmMinor=$llvmMinor" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

          - name: Get LLVM ${{steps.llvm.outputs.llvmMajor}}
            shell: bash
            run: |
                wget "https://github.com/cherryridge/dep_llvm/releases/download/${{steps.llvm.outputs.llvmMajor}}/llvm_linux_x64.7z" -O llvm.7z
                7z x llvm.7z -ollvm
                $prefix = "${{github.workspace}}/llvm"
                echo "LLVM_SYS_${{steps.llvm.outputs.sysVersion}}_PREFIX=$prefix" >> $GITHUB_ENV
                echo "LLVM_CONFIG_PATH=$prefix/bin/llvm-config" >> $GITHUB_ENV
                echo "$prefix/bin" >> $GITHUB_PATH

          - name: Build Linux x64 Debug
            shell: bash
            run: |
                cd wasmer
                cargo rustc -p wasmer-c-api --target x86_64-unknown-linux-gnu --no-default-features --features "llvm,wat" -- -Cdebuginfo=2 --crate-type=staticlib

          - name: Build Linux x64 Release
            shell: bash
            run: |
                cd wasmer
                cargo rustc -p wasmer-c-api --target x86_64-unknown-linux-gnu --no-default-features --features "llvm,wat" --release -- --crate-type=staticlib

          - name: Compress Product
            shell: bash
            run: |
                echo ${{inputs.commit-sha}} >> VERSION.txt
                mkdir -p temp/include
                cp -a wasmer/lib/c-api/tests/wasm-c-api/include/* temp/include
                cp wasmer/lib/c-api/wasmer.h temp/include
                cp wasmer/lib/c-api/wasmer_wasm.h temp/include
                7z a wasmer_linux_x64_debug.7z ./wasmer/target/x86_64-unknown-linux-gnu/debug/libwasmer.a ./temp/include VERSION.txt
                7z a wasmer_linux_x64_release.7z ./wasmer/target/x86_64-unknown-linux-gnu/release/libwasmer.a ./temp/include VERSION.txt

          - name: Upload Archive
            uses: actions/upload-artifact@v4
            with:
                name: wasmer_linux_x64
                path: |
                    *.7z
                retention-days: 7

    arm64:
        runs-on: ubuntu-latest
        steps:

          - name: Install Cross Compiler Toolchain
            shell: bash
            run: |
                sudo apt update
                sudo apt install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
                mkdir -p .cargo
                cat > .cargo/config.toml <<'EOF'
                [target.aarch64-unknown-linux-gnu]
                linker = "aarch64-linux-gnu-gcc"
                ar = "aarch64-linux-gnu-ar"
                EOF
                rustup target add aarch64-unknown-linux-gnu

          - name: Checkout Wasmer
            uses: actions/checkout@v4
            with:
                repository: wasmerio/wasmer
                path: wasmer
                ref: ${{inputs.commit-sha}}
                submodules: recursive

          - name: Install Rust
            uses: dtolnay/rust-toolchain@v1
            with:
                toolchain: stable
                targets: aarch64-unknown-linux-gnu

          - name: Resolve LLVM Version
            shell: bash
            id: llvm
            run: |
                cd wasmer
                $metajson = cargo metadata --format-version=1 --features "wasmer-c-api/llvm,wasmer-c-api/wat" --no-default-features | ConvertFrom-Json -AsHashTable
                $pkg = $metajson.packages | Where-Object { $_.name -eq "llvm-sys" } | Select-Object -First 1
                $sysMajor = [int]($pkg.version.Split('.')[0])
                $llvmMajor = [math]::Floor($sysMajor / 10)
                $llvmMinor = $sysMajor % 10
                "sysMajor=$sysMajor" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
                "llvmMajor=$llvmMajor" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
                "llvmMinor=$llvmMinor" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

          - name: Get LLVM ${{steps.llvm.outputs.llvmMajor}}
            shell: bash
            run: |
                wget "https://github.com/cherryridge/dep_llvm/releases/download/${{steps.llvm.outputs.llvmMajor}}/llvm_linux_arm64.7z" -O llvm.7z
                7z x llvm.7z -ollvm
                $prefix = "${{github.workspace}}/llvm"
                echo "LLVM_SYS_${{steps.llvm.outputs.sysVersion}}_PREFIX=$prefix" >> $GITHUB_ENV
                echo "LLVM_CONFIG_PATH=$prefix/bin/llvm-config" >> $GITHUB_ENV
                echo "$prefix/bin" >> $GITHUB_PATH

          - name: Build Linux arm64 Debug
            shell: bash
            env:
                LLVM_SYS_180_PREFIX: ${{github.workspace}}/llvm
                LLVM_CONFIG_PATH: ${{github.workspace}}/llvm/bin/llvm-config
                CC_aarch64_unknown_linux-gnu: aarch64-linux-gnu-gcc
                CXX_aarch64_unknown_linux_gnu: aarch64-linux-gnu-g++
            run: |
                cd wasmer
                cargo rustc -p wasmer-c-api --target aarch64-unknown-linux-gnu --no-default-features --features "llvm,wat" -- -Cdebuginfo=2 --crate-type=staticlib

          - name: Build Linux arm64 Release
            shell: bash
            env:
                LLVM_SYS_180_PREFIX: ${{github.workspace}}/llvm
                LLVM_CONFIG_PATH: ${{github.workspace}}/llvm/bin/llvm-config
                CC_aarch64_unknown_linux-gnu: aarch64-linux-gnu-gcc
                CXX_aarch64_unknown_linux_gnu: aarch64-linux-gnu-g++
            run: |
                cd wasmer
                cargo rustc -p wasmer-c-api --target aarch64-unknown-linux-gnu --no-default-features --features "llvm,wat" --release -- --crate-type=staticlib

          - name: Compress Product
            shell: bash
            run: |
                echo ${{inputs.commit-sha}} >> VERSION.txt
                mkdir -p temp/include
                cp -a wasmer/lib/c-api/tests/wasm-c-api/include/* temp/include
                cp wasmer/lib/c-api/wasmer.h temp/include
                cp wasmer/lib/c-api/wasmer_wasm.h temp/include
                7z a wasmer_linux_arm64_debug.7z ./wasmer/target/aarch64-unknown-linux-gnu/debug/libwasmer.a ./temp/include VERSION.txt
                7z a wasmer_linux_arm64_release.7z ./wasmer/target/aarch64-unknown-linux-gnu/release/libwasmer.a ./temp/include VERSION.txt

          - name: Upload Archive
            uses: actions/upload-artifact@v4
            with:
                name: wasmer_linux_arm64
                path: |
                    *.7z
                retention-days: 7