name: Build on Windows

on:
    workflow_call:
        inputs:
            commit-sha:
                type: string
                required: true
        outputs:
            runid:
                value: ${{github.run_id}}
    workflow_dispatch:
        inputs:
            commit-sha:
                type: string
                description: Target commit
                required: true

jobs:
    build:
        runs-on: windows-latest
        steps:

          - name: Checkout Wasmer
            uses: actions/checkout@v4
            with:
                repository: wasmerio/wasmer
                path: wasmer
                ref: ${{inputs.commit-sha}}
                submodules: recursive

          - name: Install Rust
            uses: dtolnay/rust-toolchain@v1
            with:
                toolchain: stable
                targets: x86_64-pc-windows-msvc, aarch64-pc-windows-msvc

          - name: Build Windows x64 Debug
            shell: pwsh
            run: |
                cd wasmer
                cargo build -p wasmer-c-api --target x86_64-pc-windows-msvc
                dir
                cd target
                dir

          - name: Get Artifact
            shell: pwsh
            run: |
                7z a wasmer.7z .\wasmer\target\*

          - name: Upload Archive
            uses: actions/upload-artifact@v4
            with:
                name: wasmer_windows
                path: |
                    *.7z
                retention-days: 7