name: Build on Windows

on:
    workflow_call:
        inputs:
            commit-sha:
                type: string
                required: true
        outputs:
            runid:
                value: ${{github.run_id}}
    workflow_dispatch:
        inputs:
            commit-sha:
                type: string
                description: Target commit
                required: true

jobs:
    build:
        runs-on: windows-latest
        steps:

          - name: Checkout Wasmer
            uses: actions/checkout@v4
            with:
                repository: wasmerio/wasmer
                path: wasmer
                ref: ${{inputs.commit-sha}}
                submodules: recursive

          - name: Install Rust
            uses: dtolnay/rust-toolchain@v1
            with:
                toolchain: stable
                targets: x86_64-pc-windows-msvc, aarch64-pc-windows-msvc

          - name: Resolve LLVM Version
            shell: pwsh
            id: llvm
            run: |
                $metajson = cargo metadata -p wasmer-c-api --features "$env:WASMER_FEATURES" --no-default-features --format-version=1 | ConvertFrom-Json
                $pkg = $metajson.packages | Where-Object { $_.name -eq "llvm-sys" } | Select-Object -First 1
                $sysMajor = [int]($pkg.version.Split('.')[0])
                $llvmMajor = [math]::Floor($sysMajor / 10)
                $llvmMinor = $sysMajor % 10
                $version = "$llvmMajor.$llvmMinor"
                "sysMajor=$sysMajor" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
                "version=$version" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

          - name: Install LLVM
            uses: KyleMayes/install-llvm-action@v2
            with:
                version: ${{steps.llvm.outputs.version}}

          - name: Config LLVM
            shell: pwsh
            run: |
                "LLVM_SYS_${{steps.llvm.outputs.sysMajor}}_PREFIX=${{env.LLVM_PATH}}" | Out-File $env:GITHUB_ENV -Append

          - name: Build Windows x64 Debug
            shell: pwsh
            run: |
                cd wasmer
                cargo rustc -p wasmer-c-api --target x86_64-pc-windows-msvc --no-default-features --features "llvm,wat" -- -Cdebuginfo=2 --crate-type=staticlib

          - name: Build Windows x64 Release
            shell: pwsh
            run: |
                cd wasmer
                cargo rustc -p wasmer-c-api --target x86_64-pc-windows-msvc --no-default-features --features "llvm,wat" --release -- --crate-type=staticlib

          - name: Build Windows arm64 Debug
            shell: pwsh
            run: |
                cd wasmer
                cargo rustc -p wasmer-c-api --target aarch64-pc-windows-msvc --no-default-features --features "llvm,wat" -- -Cdebuginfo=2 --crate-type=staticlib

          - name: Build Windows arm64 Release
            shell: pwsh
            run: |
                cd wasmer
                cargo rustc -p wasmer-c-api --target aarch64-pc-windows-msvc --no-default-features --features "llvm,wat" --release -- --crate-type=staticlib

          - name: Compress Product
            shell: pwsh
            run: |
                echo ${{inputs.commit-sha}} >> VERSION.txt
                mkdir temp\include
                cp -r wasmer\lib\c-api\tests\wasm-c-api\include\* temp\include
                cp wasmer\lib\c-api\wasmer.h temp\include
                cp wasmer\lib\c-api\wasmer_wasm.h temp\include
                7z a wasmer_windows_x64_debug.7z .\wasmer\target\x86_64-pc-windows-msvc\debug\wasmer.lib .\wasmer\target\x86_64-pc-windows-msvc\debug\wasmer.pdb .\temp\include VERSION.txt
                7z a wasmer_windows_x64_release.7z .\wasmer\target\x86_64-pc-windows-msvc\release\wasmer.lib .\temp\include VERSION.txt
                7z a wasmer_windows_arm64_debug.7z .\wasmer\target\aarch64-pc-windows-msvc\debug\wasmer.lib .\wasmer\target\aarch64-pc-windows-msvc\debug\wasmer.pdb .\temp\include VERSION.txt
                7z a wasmer_windows_arm64_release.7z .\wasmer\target\aarch64-pc-windows-msvc\release\wasmer.lib .\temp\include VERSION.txt

          - name: Upload Archive
            uses: actions/upload-artifact@v4
            with:
                name: wasmer_windows
                path: |
                    *.7z
                retention-days: 7