name: Build on Windows

on:
    workflow_call:
        inputs:
            commit-sha:
                type: string
                required: true
        outputs:
            runid:
                value: ${{github.run_id}}
    workflow_dispatch:
        inputs:
            commit-sha:
                type: string
                description: Target commit
                required: true

jobs:
    x64:
        runs-on: windows-latest
        steps:

          - name: Checkout Wasmer
            uses: actions/checkout@v4
            with:
                repository: wasmerio/wasmer
                path: wasmer
                ref: ${{inputs.commit-sha}}
                submodules: recursive

          - name: Install Rust
            uses: dtolnay/rust-toolchain@v1
            with:
                toolchain: stable
                targets: x86_64-pc-windows-msvc

          - name: Resolve LLVM Version
            shell: pwsh
            id: llvm
            run: |
                cd wasmer
                $metajson = cargo metadata --format-version=1 --features "wasmer-c-api/llvm,wasmer-c-api/wat" --no-default-features | ConvertFrom-Json -AsHashTable
                $pkg = $metajson.packages | Where-Object { $_.name -eq "llvm-sys" } | Select-Object -First 1
                $sysMajor = [int]($pkg.version.Split('.')[0])
                $llvmMajor = [math]::Floor($sysMajor / 10)
                $llvmMinor = $sysMajor % 10
                "sysMajor=$sysMajor" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
                "llvmMajor=$llvmMajor" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
                "llvmMinor=$llvmMinor" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

          - name: Get LLVM ${{steps.llvm.outputs.llvmMajor}}
            shell: pwsh
            run: |
                Invoke-WebRequest -Uri "https://github.com/wasmerio/llvm-custom-builds/releases/download/${{steps.llvm.outputs.llvmMajor}}.x/llvm-windows-amd64.tar.xz" -OutFile llvm.tar.xz
                tar -xf .\llvm.tar.xzz -C .\llvm
                $prefix = "${{github.workspace}}/llvm"
                "LLVM_SYS_${{steps.llvm.outputs.sysMajor}}_PREFIX=$prefix" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
                "LLVM_CONFIG_PATH=$prefix/bin/llvm-config.exe" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
                "$prefix/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

          - name: Build Windows x64 Debug
            shell: pwsh
            run: |
                cd wasmer
                cargo rustc -p wasmer-c-api --target x86_64-pc-windows-msvc --no-default-features --features "llvm,wat" -- -Cdebuginfo=2 -Ctarget-feature=+crt-static --crate-type=staticlib

          - name: Build Windows x64 Release
            shell: pwsh
            run: |
                cd wasmer
                cargo rustc -p wasmer-c-api --target x86_64-pc-windows-msvc --no-default-features --features "llvm,wat" --release -- -Ctarget-feature=+crt-static --crate-type=staticlib

          - name: Compress Product
            shell: pwsh
            run: |
                echo ${{inputs.commit-sha}} >> VERSION.txt
                mkdir temp\include
                cp -r wasmer\lib\c-api\tests\wasm-c-api\include\* temp\include
                cp wasmer\lib\c-api\wasmer.h temp\include
                cp wasmer\lib\c-api\wasmer_wasm.h temp\include
                7z a wasmer_windows_x64_debug.7z .\wasmer\target\x86_64-pc-windows-msvc\debug\wasmer.lib .\wasmer\target\x86_64-pc-windows-msvc\debug\wasmer.pdb .\temp\include VERSION.txt
                7z a wasmer_windows_x64_release.7z .\wasmer\target\x86_64-pc-windows-msvc\release\wasmer.lib .\temp\include VERSION.txt
                dir

          - name: Upload Archive
            uses: actions/upload-artifact@v4
            with:
                name: wasmer_windows_x64
                path: |
                    .\wasmer_windows_x64_debug.7z, .\wasmer_windows_x64_release.7z
                retention-days: 7

    arm64:
        runs-on: windows-11-arm
        steps:

          - name: Checkout Wasmer
            uses: actions/checkout@v4
            with:
                repository: wasmerio/wasmer
                path: wasmer
                ref: ${{inputs.commit-sha}}
                submodules: recursive

          - name: Install Rust
            uses: dtolnay/rust-toolchain@v1
            with:
                toolchain: stable
                targets: aarch64-pc-windows-msvc

          - name: Build Windows arm64 Debug (Cranelift)
            shell: pwsh
            run: |
                cd wasmer
                cargo rustc -p wasmer-c-api --target aarch64-pc-windows-msvc --no-default-features --features "cranelift,wat" -- -Cdebuginfo=2 -Ctarget-feature=+crt-static --crate-type=staticlib 

          - name: Build Windows arm64 Release (Cranelift)
            shell: pwsh
            run: |
                cd wasmer
                cargo rustc -p wasmer-c-api --target aarch64-pc-windows-msvc --no-default-features --features "cranelift,wat" --release -- -Ctarget-feature=+crt-static --crate-type=staticlib

          - name: Compress Product
            shell: pwsh
            run: |
                echo ${{inputs.commit-sha}} >> VERSION.txt
                mkdir temp\include
                cp -r wasmer\lib\c-api\tests\wasm-c-api\include\* temp\include
                cp wasmer\lib\c-api\wasmer.h temp\include
                cp wasmer\lib\c-api\wasmer_wasm.h temp\include
                7z a wasmer_windows_arm64_debug.7z .\wasmer\target\aarch64-pc-windows-msvc\debug\wasmer.lib .\wasmer\target\aarch64-pc-windows-msvc\debug\wasmer.pdb .\temp\include VERSION.txt
                7z a wasmer_windows_arm64_release.7z .\wasmer\target\aarch64-pc-windows-msvc\release\wasmer.lib .\temp\include VERSION.txt

          - name: Upload Archive
            uses: actions/upload-artifact@v4
            with:
                name: wasmer_windows_arm64
                path: |
                    .\wasmer_windows_arm64_debug.7z, .\wasmer_windows_arm64_release.7z
                retention-days: 7